language: python

matrix:
  include:
  - os: linux
    python: 3.6
    env: PYTHON=3.6 PANDAS=MASTER COVERAGE='false' LINT='true'
env:

before_install:
  - echo "before_install"
  - source ci/travis_process_gbq_encryption.sh

install:
  # Upgrade setuptools and pip to work around
  # https://github.com/pypa/setuptools/issues/885
  - pip install --upgrade setuptools pip
  - pip install --upgrade google-cloud-bigquery

script:
  - python cleanup.py
